import { expect, test } from "bun:test";
import { lstat, mkdtemp, readFile, realpath, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { composeTarget } from "./compose-target";
import { fixture, trust } from "./fixtures/composition/fixture";

test("allowlist composition preserves binary bytes and executable mode reproducibly without copying dead paths", async () => {
  const f = await fixture();
  const out = await realpath(await mkdtemp(join(tmpdir(), "compose-out-")));
  try {
    const a = await composeTarget(f.input, f.policy, join(out, "one"));
    const b = await composeTarget(f.input, f.policy, join(out, "two"));
    expect(a.treeDigest).toBe(b.treeDigest);
    expect(await readFile(join(a.directory, "main.bin"))).toEqual(Buffer.from([255, 0, 13, 10]));
    expect((await lstat(join(a.directory, "main.bin"))).mode & 0o111).toBe(0o111);
    expect(await Bun.file(join(a.directory, "dead.txt")).exists()).toBe(false);
    await expect(composeTarget(f.input, f.policy, join(out, "one"))).rejects.toThrow(
      "composition-rejected",
    );
    expect(await readFile(join(f.root, "dead.txt"), "utf8")).toBe("not retained");
  } finally {
    await rm(f.root, { recursive: true, force: true });
    await rm(out, { recursive: true, force: true });
  }
});
test.each([
  "bytes",
  "missing",
  "rights",
  "traversal",
  "collision",
  "unreviewed",
])("rejects %s before target creation", async (attack) => {
  const f = await fixture();
  const out = await realpath(await mkdtemp(join(tmpdir(), "compose-bad-")));
  try {
    const file = f.input.files[0];
    const decision = f.input.decisions[0];
    if (!file || !decision) throw new Error("fixture");
    if (attack === "bytes") file.sourceDigest = "c".repeat(64);
    if (attack === "missing") {
      f.input.files.pop();
      f.input.decisions.pop();
    }
    if (attack === "rights") f.input.licenses.files = [];
    if (
      (attack === "traversal" || attack === "collision") &&
      decision.disposition.kind === "retain"
    )
      decision.disposition.targetPath = attack === "traversal" ? "../escape" : "LICENSE";
    if (attack === "unreviewed") f.input.slug = "contracts";
    const policy = attack === "unreviewed" ? f.policy : trust(f.input);
    await expect(composeTarget(f.input, policy, join(out, "target"))).rejects.toThrow(
      "composition-rejected",
    );
    expect(await Bun.file(join(out, "target", "db-inspect", "main.bin")).exists()).toBe(false);
  } finally {
    await rm(f.root, { recursive: true, force: true });
    await rm(out, { recursive: true, force: true });
  }
});

test.each([
  {
    recipeId: "identity.v1" as const,
    canonicalBytes: Buffer.from([255, 0, 13, 10]),
    targetBytes: Buffer.from([255, 0, 13, 10]),
  },
  {
    recipeId: "canonical-json.v1" as const,
    canonicalBytes: Buffer.from('{"z":1,"a":2}\r\n'),
    targetBytes: Buffer.from('{\n  "a": 2,\n  "z": 1\n}\n'),
  },
])("$recipeId verifies distinct source and generated target digests", async ({
  recipeId,
  canonicalBytes,
  targetBytes,
}) => {
  const { fileId } = await import("./reachability");
  const { digestEvidence } = await import("./license-audit");
  const { sha, git } = await import("./fixtures/composition/fixture");
  const { writeFile } = await import("node:fs/promises");
  const f = await fixture(canonicalBytes);
  const out = await realpath(await mkdtemp(join(tmpdir(), "compose-generated-")));
  try {
    await writeFile(join(f.root, "generated.txt"), "old generated bytes");
    await git(f.root, "add", "generated.txt");
    await git(
      f.root,
      "-c",
      "commit.gpgsign=false",
      "-c",
      "user.name=Synthetic",
      "-c",
      "user.email=fixture@example.invalid",
      "commit",
      "-qm",
      "Generated fixture",
    );
    const commit = await git(f.root, "rev-parse", "HEAD");
    const original = f.input.files[0];
    if (!original) throw new Error("fixture");
    f.input.files = f.input.files.map((file) => ({ ...file, sourceCommit: commit }));
    const canonical = f.input.files[0];
    const license = f.input.files[1];
    if (!canonical || !license) throw new Error("fixture");
    const generated = {
      ...canonical,
      sourcePath: "generated.txt",
      sourceDigest: sha("old generated bytes"),
      role: "generated" as const,
    };
    f.input.files.push(generated);
    f.input.sources[0] = { source: "db-inspect", root: f.root, commit };
    const entry = fileId(canonical);
    f.input.entryPoints = [entry];
    f.input.edges = [{ consumer: entry, provider: fileId(generated), kind: "build" }];
    f.input.decisions = f.input.files.map((file) => ({
      file: fileId(file),
      disposition:
        file.role === "generated"
          ? {
              kind: "generate",
              target: "db-inspect",
              targetPath: "generated.txt",
              canonicalSource: entry,
            }
          : file.sourcePath === "dead.txt"
            ? { kind: "delete", reason: "dead" }
            : {
                kind: "retain",
                target: "db-inspect",
                targetPath: file.sourcePath,
                entryPoint: entry,
                ...(file.sourcePath === "LICENSE"
                  ? { supportFor: [entry], supportEvidenceDigest: "a".repeat(64) }
                  : {}),
              },
    }));
    f.input.licenses.files = f.input.licenses.files.map((file) => ({ ...file, commit }));
    const first = f.input.licenses.files[0];
    if (!first) throw new Error("fixture");
    f.input.licenses.files.push({
      ...first,
      path: "generated.txt",
      targetPath: "generated.txt",
      contentDigest: generated.sourceDigest,
    });
    const recipe = {
      file: fileId(generated),
      canonicalSource: entry,
      recipe: recipeId,
      targetDigest: sha(targetBytes),
      reviewDigest: "d".repeat(64),
    };
    f.input.generation = [recipe];
    const policy = trust(f.input);
    await expect(composeTarget(f.input, policy, join(out, "missing"))).rejects.toThrow(
      "composition-rejected",
    );
    policy.generationDigests = [digestEvidence(recipe)];
    const composed = await composeTarget(f.input, policy, join(out, "valid"));
    expect(await readFile(join(composed.directory, "generated.txt"))).toEqual(targetBytes);
    expect(composed.files.find((file) => file.path === "generated.txt")?.digest).not.toBe(
      generated.sourceDigest,
    );
    recipe.targetDigest = "0".repeat(64);
    const stale = trust(f.input);
    stale.generationDigests = [digestEvidence(recipe)];
    await expect(composeTarget(f.input, stale, join(out, "wrong-digest"))).rejects.toThrow(
      "composition-rejected",
    );
  } finally {
    await rm(f.root, { recursive: true, force: true });
    await rm(out, { recursive: true, force: true });
  }
});

test("committed symlinks and unclassified added paths fail closed", async () => {
  const { symlink } = await import("node:fs/promises");
  const { git } = await import("./fixtures/composition/fixture");
  const f = await fixture();
  const out = await realpath(await mkdtemp(join(tmpdir(), "compose-link-")));
  try {
    await symlink("/outside", join(f.root, "escape"));
    await git(f.root, "add", "escape");
    await git(
      f.root,
      "-c",
      "commit.gpgsign=false",
      "-c",
      "user.name=Synthetic",
      "-c",
      "user.email=fixture@example.invalid",
      "commit",
      "-qm",
      "Symlink fixture",
    );
    const commit = await git(f.root, "rev-parse", "HEAD");
    const source = f.input.sources[0];
    if (!source) throw new Error("fixture");
    source.commit = commit;
    await expect(composeTarget(f.input, trust(f.input), join(out, "result"))).rejects.toThrow(
      "composition-rejected",
    );
  } finally {
    await rm(f.root, { recursive: true, force: true });
    await rm(out, { recursive: true, force: true });
  }
});

test("CLI requires independently pinned policy and emits opaque composition evidence", async () => {
  const { writeFile } = await import("node:fs/promises");
  const { sha } = await import("./fixtures/composition/fixture");
  const f = await fixture();
  const out = await realpath(await mkdtemp(join(tmpdir(), "compose-cli-")));
  try {
    const input = join(out, "input.json");
    const policy = join(out, "policy.json");
    const bytes = JSON.stringify(f.policy);
    await writeFile(input, JSON.stringify(f.input));
    await writeFile(policy, bytes);
    const child = Bun.spawn(
      [
        process.execPath,
        join(import.meta.dir, "compose-target.ts"),
        "--input",
        input,
        "--policy",
        policy,
        "--policy-sha256",
        sha(bytes),
        "--output",
        join(out, "run"),
      ],
      { stdout: "pipe", stderr: "pipe" },
    );
    const [stdout, stderr, exit] = await Promise.all([
      new Response(child.stdout).text(),
      new Response(child.stderr).text(),
      child.exited,
    ]);
    expect(exit).toBe(0);
    expect(stderr).toBe("");
    expect(JSON.parse(stdout).treeDigest).toMatch(/^[a-f0-9]{64}$/);
    expect(stdout).not.toContain(f.root);
    expect(await Bun.file(join(out, "run", "db-inspect", "main.bin")).exists()).toBe(true);
  } finally {
    await rm(f.root, { recursive: true, force: true });
    await rm(out, { recursive: true, force: true });
  }
});

test("composition refuses output inside a source worktree", async () => {
  const f = await fixture();
  try {
    await expect(composeTarget(f.input, f.policy, join(f.root, "composed"))).rejects.toThrow(
      "composition-rejected",
    );
    expect(await Bun.file(join(f.root, "composed", "db-inspect", "main.bin")).exists()).toBe(false);
  } finally {
    await rm(f.root, { recursive: true, force: true });
  }
});

test("composition pins its first executable before applying the isolated environment", async () => {
  const out = await realpath(await mkdtemp(join(tmpdir(), "compose-path-")));
  try {
    const marker = join(out, "unexpected-executable");
    await writeFile(
      join(out, "env"),
      '#!/bin/sh\nprintf invoked > "$C6_PROBE_MARKER"\nexec /usr/bin/env "$@"\n',
      { mode: 0o700 },
    );
    const probe = Bun.spawn(
      [
        process.execPath,
        "-e",
        "import { compositionGit } from './tools/migration/compose-target'; await compositionGit(process.cwd(), 'rev-parse', '--is-inside-work-tree');",
      ],
      {
        cwd: join(import.meta.dir, "../.."),
        env: { ...process.env, PATH: `${out}:/usr/bin:/bin`, C6_PROBE_MARKER: marker },
        stdout: "ignore",
        stderr: "ignore",
      },
    );
    expect(await probe.exited).toBe(0);
    expect(await Bun.file(marker).exists()).toBe(false);
  } finally {
    await rm(out, { recursive: true, force: true });
  }
});
